### PR TITLE
remove kibana index handlers

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by sosiouxme** [comment]
@jimmidyson @jcantrill reviews welcome.

**Comment by jimmidyson** [comment]
@sosiouxme I'm sure they are.

**Comment by jimmidyson** [comment]
I'd normally like to see this as separate PRs: remove kibana stuff & fix up oauth stuff.

Can you also detail what changes this brings to oauth handling? Hard to review without knowing what changes you're trying to introduce or problems you're trying to solve.

**Comment by sosiouxme** [comment]
Well the commit messages sum it up...

I can split into two PRs and provide detail.

**Comment by jimmidyson** [comment]
Thanks! When reviewing PRs it's easier to have the summary in the PR rather than having to look at individual commit messages.

**Comment by sosiouxme** [comment]
@jimmi this one is just the kibana handler removal.

**Comment by jcantrill** [comment]
LGTM :)

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
